def getParameters(args) {
    return {
        parameterSeparatorDefinition {
            name('COMMIT_OPTIONS_HEADER')
            separatorStyle('')
            sectionHeader(args.fabricCommitOptionsParamsSeparatorDesc)
            sectionHeaderStyle('')
        }
        validatingStringParameterDefinition {
            name('AUTHOR_EMAIL')
            defaultValue('')
            regex('^[a-zA-Z0-9!#$%&\'*+/=?^_`{|}~-]+(?:\\.[a-zA-Z0-9!#$%&\'*+/=?^_`{|}~-]+)*@(?:[a-zA-Z0-9](?:[a-zA-Z0-9-]*[a-zA-Z0-9])?\\.)+[a-zA-Z0-9](?:[a-zA-Z0-9-]*[a-zA-Z0-9])?$')
            failedValidationMessage('Please provide valid e-mail address!')
            description('This field required for git client configuration, to be able to push changes to remote repository.')
        }
        stringParam('COMMIT_AUTHOR', '', 'Please provide author for commit. By default "AppFactory" value will be set.')
        stringParam('COMMIT_MESSAGE', '', 'Please provide message for commit. By default autogenerated text will be set.')
    }
}
